export const ROLES_LOOKUP = {
    ADMIN: 'ADMIN',
    USER: 'USER',
    QUIZ_REVIEWER: 'QUIZ_REVIEWER',
    GAME_REVIEWER: 'GAME_REVIEWER',
    TRANSLATION_REVIEWER: 'TRANSLATION_REVIEWER',
    TRANSLATOR: 'TRANSLATOR',
    GAME_MANAGER: 'GAME_MANAGER',
}
